services:
  postgres:
    image: 'postgres:16.3'
    container_name: vroomdb
    environment:
      - 'POSTGRES_DB=vroom'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'