spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate

server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:username}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
